### ISSUE TITLE
sold out

### ISSUE THREAD

**Issue by jerabaul29** [sparkfunX/Qwiic_Power_Switch#3]
FYI / if other people are looking for this: seems to be sold out, but mouser still has some: https://no.mouser.com/ProductDetail/SparkFun/SPX-16740?qs=DPoM0jnrROVJN3KjZlloUg%3D%3D .

**Comment by jerabaul29** [comment]
This is sold out at both Sparkfun, Digikey, and Mouser. Any idea where this can be bought? We need it for some of our Artemis Global Tracker-based designs.

**Comment by PaulZC** [comment]
Hi JR,

These are in the production queue. They should be available in a week or so.

Best wishes,
Paul

**Comment by jerabaul29** [comment]
Perfect, many thanks for the update :) . FYI @gauteh , should be available soon :) .

**Comment by PaulZC** [comment]
Closing…. 114 pieces currently in stock.
